// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlpNbzbys2ZKsnY5KY1oJQuPgmAYzzyr8',
    appId: '1:1088055574039:web:5f22e6fa0f85f077a3a652',
    messagingSenderId: '1088055574039',
    projectId: 'registration-2b7e0',
    authDomain: 'registration-2b7e0.firebaseapp.com',
    storageBucket: 'registration-2b7e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7E9dovbD4FXzLMMVEzV7Z6hqkdaGhLM',
    appId: '1:1088055574039:android:20e5eb0bba704c43a3a652',
    messagingSenderId: '1088055574039',
    projectId: 'registration-2b7e0',
    storageBucket: 'registration-2b7e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRFSq5mIajgp325vwq1k_L257QhCDIBSU',
    appId: '1:1088055574039:ios:599796131ba98d62a3a652',
    messagingSenderId: '1088055574039',
    projectId: 'registration-2b7e0',
    storageBucket: 'registration-2b7e0.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRFSq5mIajgp325vwq1k_L257QhCDIBSU',
    appId: '1:1088055574039:ios:599796131ba98d62a3a652',
    messagingSenderId: '1088055574039',
    projectId: 'registration-2b7e0',
    storageBucket: 'registration-2b7e0.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlpNbzbys2ZKsnY5KY1oJQuPgmAYzzyr8',
    appId: '1:1088055574039:web:1376dabd7c0f7a0ba3a652',
    messagingSenderId: '1088055574039',
    projectId: 'registration-2b7e0',
    authDomain: 'registration-2b7e0.firebaseapp.com',
    storageBucket: 'registration-2b7e0.firebasestorage.app',
  );
}
